"""
Unit tests for the US Yield Curve Macro Dashboard.
Run with: pytest tests/
"""

import pytest
import numpy as np
from scipy.stats import norm


# ---------------------------------------------------------------------------
# Helpers (minimal stubs so tests run without external dependencies)
# ---------------------------------------------------------------------------

def probit_probability(alpha: float, beta: float, spread: float) -> float:
    """Univariate NY-Fed probit: P(recession in 12m) = Phi(alpha + beta*spread)."""
        return float(norm.cdf(alpha + beta * spread))


        def multivariate_probit(spread_10y_3m: float, hy_spread: float, ffr: float) -> float:
            """Favara et al. (2016) multivariate probit."""
                z = -2.40 - 0.55 * spread_10y_3m + 0.08 * hy_spread + 0.10 * ffr
                    return float(norm.cdf(z))


                    def detect_inversion(spread_10y_2y: float) -> bool:
                        """Return True when the 10Y-2Y spread is negative (curve inverted)."""
                            return spread_10y_2y < 0


                            # ---------------------------------------------------------------------------
                            # Probit model tests
                            # ---------------------------------------------------------------------------

                            class TestUnivariateProbit:
                                """Tests for the univariate NY-Fed probit model."""

                                    def test_output_between_0_and_1(self):
                                            """Probability must always lie in [0, 1]."""
                                                    alpha, beta = -0.6135, -0.7425  # Estrella & Mishkin 1998
                                                            for spread in [-3.0, -1.0, 0.0, 1.0, 3.0]:
                                                                        p = probit_probability(alpha, beta, spread)
                                                                                    assert 0.0 <= p <= 1.0, f"Probability out of bounds for spread={spread}: {p}"

                                                                                        def test_negative_spread_raises_recession_probability(self):
                                                                                                """An inverted curve (negative spread) should push probability higher."""
                                                                                                        alpha, beta = -0.6135, -0.7425
                                                                                                                p_inverted = probit_probability(alpha, beta, -1.5)
                                                                                                                        p_normal = probit_probability(alpha, beta, 1.5)
                                                                                                                                assert p_inverted > p_normal
                                                                                                                                
                                                                                                                                    def test_positive_beta_fallback(self):
                                                                                                                                            """
                                                                                                                                                    When estimated beta turns positive (economically implausible),
                                                                                                                                                            the model should fall back to the 1998 hardcoded values.
                                                                                                                                                                    """
                                                                                                                                                                            estimated_beta = 0.30  # implausible sign
                                                                                                                                                                                    fallback_beta = -0.7425
                                                                                                                                                                                    
                                                                                                                                                                                            # Simulate fallback logic
                                                                                                                                                                                                    beta_used = fallback_beta if estimated_beta > 0 else estimated_beta
                                                                                                                                                                                                            assert beta_used == fallback_beta
                                                                                                                                                                                                            
                                                                                                                                                                                                                def test_extreme_positive_spread_low_probability(self):
                                                                                                                                                                                                                        """A very steep curve should yield near-zero recession probability."""
                                                                                                                                                                                                                                alpha, beta = -0.6135, -0.7425
                                                                                                                                                                                                                                        p = probit_probability(alpha, beta, 5.0)
                                                                                                                                                                                                                                                assert p < 0.05
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    def test_extreme_negative_spread_high_probability(self):
                                                                                                                                                                                                                                                            """A very deep inversion should yield high recession probability."""
                                                                                                                                                                                                                                                                    alpha, beta = -0.6135, -0.7425
                                                                                                                                                                                                                                                                            p = probit_probability(alpha, beta, -5.0)
                                                                                                                                                                                                                                                                                    assert p > 0.90
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                    # ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                                    # Multivariate probit model tests
                                                                                                                                                                                                                                                                                    # ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                    class TestMultivariateProbit:
                                                                                                                                                                                                                                                                                        """Tests for the Favara et al. (2016) multivariate probit model."""
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            def test_output_between_0_and_1(self):
                                                                                                                                                                                                                                                                                                    """Probability must always lie in [0, 1]."""
                                                                                                                                                                                                                                                                                                            for spread, hy, ffr in [(-1.5, 400, 2.5), (0.5, 300, 5.0), (2.0, 200, 0.25)]:
                                                                                                                                                                                                                                                                                                                        p = multivariate_probit(spread, hy, ffr)
                                                                                                                                                                                                                                                                                                                                    assert 0.0 <= p <= 1.0
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        def test_high_hy_spread_increases_recession_probability(self):
                                                                                                                                                                                                                                                                                                                                                """Higher HY spread (financial stress) should raise recession probability."""
                                                                                                                                                                                                                                                                                                                                                        p_low_hy = multivariate_probit(0.0, 300, 3.0)
                                                                                                                                                                                                                                                                                                                                                                p_high_hy = multivariate_probit(0.0, 800, 3.0)
                                                                                                                                                                                                                                                                                                                                                                        assert p_high_hy > p_low_hy
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                            def test_high_ffr_increases_recession_probability(self):
                                                                                                                                                                                                                                                                                                                                                                                    """Higher Fed Funds Rate should raise recession probability."""
                                                                                                                                                                                                                                                                                                                                                                                            p_low_ffr = multivariate_probit(0.0, 400, 0.25)
                                                                                                                                                                                                                                                                                                                                                                                                    p_high_ffr = multivariate_probit(0.0, 400, 8.0)
                                                                                                                                                                                                                                                                                                                                                                                                            assert p_high_ffr > p_low_ffr
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                            # ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                            # Inversion detection tests
                                                                                                                                                                                                                                                                                                                                                                                                            # ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                            class TestInversionDetection:
                                                                                                                                                                                                                                                                                                                                                                                                                """Tests for yield curve inversion detection."""
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    def test_negative_spread_is_inverted(self):
                                                                                                                                                                                                                                                                                                                                                                                                                            assert detect_inversion(-0.01) is True
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                def test_positive_spread_is_not_inverted(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                        assert detect_inversion(0.50) is False
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_zero_spread_is_not_inverted(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Zero spread is flat, not inverted."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert detect_inversion(0.0) is False
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Alert threshold tests
                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                            class TestAlertThresholds:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Validate that default alert thresholds produce the expected triggers."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    THRESHOLDS = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "inversion": 0,        # 10Y-2Y < 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "recession_prob": 0.30, # univariate or multivariate > 30%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "hy_spread": 600,       # bps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "term_premium": -0.5,   # pp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_inversion_alert_triggers_correctly(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    spread = -0.10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            assert spread < self.THRESHOLDS["inversion"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_recession_prob_alert_triggers_correctly(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prob = 0.35
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert prob > self.THRESHOLDS["recession_prob"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def test_hy_spread_alert_triggers_correctly(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            hy = 650
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert hy > self.THRESHOLDS["hy_spread"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_term_premium_alert_triggers_correctly(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tp = -0.75
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assert tp < self.THRESHOLDS["term_premium"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
